server {
    listen 443 ssl;
    server_name wotlk.amatol.blog;

    limit_conn per_ip_connections 8;
    limit_conn_status 429;
    limit_req zone=per_ip_requests burst=30 nodelay;
    limit_req_status 429;
    limit_req_log_level error;

    ssl_certificate /etc/letsencrypt/live/wotlk.amatol.blog/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/wotlk.amatol.blog/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location /launcher/addons/ {
        # Маленькие файлы аддонов плавно ограничиваем, не обрывая загрузку HTTP 429.
        limit_req zone=per_ip_requests burst=100;
        alias /opt/azerothcore/addons/;
        autoindex off;
        limit_except GET HEAD { deny all; }
        add_header X-Content-Type-Options nosniff always;
        limit_rate_after 10m;
        limit_rate 20m;
    }

    location /launcher/ {
        alias /srv/dreamworld-launcher/;
        autoindex off;
        limit_except GET HEAD { deny all; }
        add_header X-Content-Type-Options nosniff always;
        limit_rate_after 10m;
        limit_rate 20m;
    }

    location / {
        return 404;
    }
}

server {
    listen 80;
    server_name wotlk.amatol.blog;
    return 301 https://$host$request_uri;
}
