server {
    listen 443 ssl;
    server_name wotlk.amatol.blog;

    ssl_certificate /etc/letsencrypt/live/wotlk.amatol.blog/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/wotlk.amatol.blog/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    location /launcher/ {
        alias /srv/dreamworld-launcher/;
        autoindex off;
        limit_except GET HEAD { deny all; }
        add_header X-Content-Type-Options nosniff always;
    }

    location / {
        return 404;
    }
}

server {
    listen 80;
    server_name wotlk.amatol.blog;
    return 301 https://$host$request_uri;
}
