server {
    listen 80;
    listen [::]:80;
    server_name wotlk.amatol.blog;

    location /launcher/ {
        alias /srv/dreamworld-launcher/;
        autoindex off;
        limit_except GET HEAD { deny all; }
        add_header X-Content-Type-Options nosniff always;
    }
}
